name: Tag Latest Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version increment type (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write  # Необходимо для создания тегов

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Полная история для работы с тегами
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/vladsvdd/online_marketplace_libs.git"

      - name: Run version script
        run: |
          chmod +x ./scripts/version.sh
          ./scripts/version.sh ${{ github.event.inputs.version_type || 'patch' }}

      - name: Verify tags
        run: |
          git fetch --tags
          git tag -l